packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  bufferutil: false
  core-js: false
  esbuild: true
  unrs-resolver: true
  utf-8-validate: false
minimumReleaseAgeExclude:
  - "@clerk/backend@3.8.4"
  - "@clerk/react@6.11.1"
  - "@clerk/shared@4.22.0"
  - "@clerk/tanstack-react-start@1.4.9"
