/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as PricingRouteImport } from "./routes/pricing";
import { Route as ModelsRouteImport } from "./routes/models";
import { Route as AppRouteImport } from "./routes/app";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthSplatRouteImport } from "./routes/auth.$";

const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const PricingRoute = PricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => rootRouteImport,
} as any);
const ModelsRoute = ModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: "/auth/$",
  path: "/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/app": typeof AppRoute;
  "/models": typeof ModelsRoute;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/auth/$": typeof AuthSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/app": typeof AppRoute;
  "/models": typeof ModelsRoute;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/auth/$": typeof AuthSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/app": typeof AppRoute;
  "/models": typeof ModelsRoute;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/auth/$": typeof AuthSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/app"
    | "/models"
    | "/pricing"
    | "/privacy"
    | "/terms"
    | "/auth/$";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/app" | "/models" | "/pricing" | "/privacy" | "/terms" | "/auth/$";
  id:
    | "__root__"
    | "/"
    | "/app"
    | "/models"
    | "/pricing"
    | "/privacy"
    | "/terms"
    | "/auth/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRoute;
  ModelsRoute: typeof ModelsRoute;
  PricingRoute: typeof PricingRoute;
  PrivacyRoute: typeof PrivacyRoute;
  TermsRoute: typeof TermsRoute;
  AuthSplatRoute: typeof AuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pricing": {
      id: "/pricing";
      path: "/pricing";
      fullPath: "/pricing";
      preLoaderRoute: typeof PricingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/models": {
      id: "/models";
      path: "/models";
      fullPath: "/models";
      preLoaderRoute: typeof ModelsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/$": {
      id: "/auth/$";
      path: "/auth/$";
      fullPath: "/auth/$";
      preLoaderRoute: typeof AuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthSplatRoute: AuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
